config/routes.rb
Rails.application.routes.draw do

  scope '/' do
    get '/', to: 'site#index'
    get '/show', to: 'site#show'
  end

  get 'logout' => 'sessions#destroy', as: 'log_out'
  get 'login' => 'sessions#new', as: 'log_in'
  get 'sign_up' => 'users#new', as: 'sign_up'
  resources :users
  resources :sessions
  root to: 'site#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord

  attr_accessor :password
  validates_confirmation_of :password
  validates_presence_of :password, on: :create
  validates_presence_of :email
  validates_uniqueness_of :email
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    user = User.authenticate(params[:email], params[:password])
    respond_to do |format|
      if user
        session[:user_id] = user.id
        format.html { redirect_to show_path }
      else
        flash.now.alert = "Invalid email or password"
        format.html { render :new }
      end
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :require_login, :except => [:index]

  def index

  end

  def show

  end

  private
  def require_login
    unless current_user.present?
      flash[:error] = "You must be logged in to access this section"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_parameters)
    respond_to do |format|
      if @user.save
        format.html { redirect_to root_path, notice: "Successfully sign up" }
      else
        format.html { render :new, error: "Invalid input" }
      end
    end
  end

  private
  def user_parameters
    params.require(:user).permit(:password, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Authentication</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="user_nav">
      <% if current_user %>
          Logged in as <%= current_user.email %>,
          <%= link_to "Log out", log_out_path %>
      <% else %>
          <%= link_to "Sign up", sign_up_path %>
          <%= link_to "log in", log_in_path %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>

app/views/site/show.html.erb
<h1>Site#show</h1>
<p>Find me in app/views/site/show.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
    <% if @user.errors.any? %>
        <div class="error_messages">
          <ul>
            <% for message in @user.errors.full_messages %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <p>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </p>
    <p>
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation %>
    </p>
    <p class="button"><%= f.submit %></p>
<% end %>